name: p11_favorite_places_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.3.0
  uuid: ^4.5.1
  flutter_riverpod: ^2.6.1
  image_picker: ^1.2.0
  location: ^8.0.1
  http: ^1.5.0
  path: ^1.9.0
  flutter_dotenv: ^5.1.0
  google_maps_flutter: ^2.12.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - .env
